apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:17.2.2-ce.0
        ports:
        - containerPort: 80
        env:
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: gitlab-root-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: postgres-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: redis-password
        - name: REDIS_URL
          value: redis://{{ .Values.redis.external.host }}:{{ .Values.redis.external.port }}
        - name: REDIS_PORT
          value: "{{ .Values.redis.external.port }}"
        envFrom:
        - secretRef:
            name: gitlab-secret
          volumeMounts:
          - name: gitlab-data
            mountPath: "{{ .Values.persistence.mountPath }}"
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
  namespace: "{{ .Release.Namespace }}"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/gitlab 
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
  namespace: "{{ .Release.Namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi



