apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-postgresql
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-postgresql
  template:
    metadata:
      labels:
        app: gitlab-postgresql
    spec:
      containers:
      - name: postgresql
        image: "bitnami/postgresql:latest"
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: postgres-password
        - name: POSTGRESQL_USERNAME
          value: "{{ .Values.postgresql.postgresqlUsername }}"
        - name: POSTGRESQL_DATABASE
          value: "{{ .Values.postgresql.postgresqlDatabase }}"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: gitlab-postgresql
