apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: gitlab
type: Opaque
data:
  gitlab-root-password: UjNkaEB0ITM=
  postgres-password: UjNkaEB0ITM=
  redis-password: UjNkaEB0ITM=
